version: '3'

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }
  local_django_protected: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
      - local_django_protected:/app/protected
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:3.2
    ports:
      - "6379:6379"

  celeryworker:
    <<: *django
    depends_on:
      - redis
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    depends_on:
      - redis
    ports: [ ]
    command: /start-celerybeat

  flower:
    <<: *django
    ports:
      - "5555:5555"
    depends_on:
      - celeryworker
      - celerybeat
    command: /start-flower