#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


celery -A help_gamblers.taskapp worker -l INFO -n default@%h &
celery -A help_gamblers.taskapp worker -l INFO --concurrency=10 -Q offboard -n offboard1@%h &
celery -A help_gamblers.taskapp worker -l INFO --concurrency=10 -Q offboard -n offboard2@%h &
celery -A help_gamblers.taskapp worker -l INFO --concurrency=10 -Q offboard -n offboard3@%h
