#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate
python /app/manage.py collectstatic --noinput
/usr/local/bin/gunicorn help_gamblers.wsgi --bind 0.0.0.0:8000 --workers=9 --chdir=/app --reload
