#!/bin/sh

set -o errexit
set -o nounset

until timeout 10s celery -A help_gamblers.taskapp inspect ping; do
    >&2 echo "Celery workers not available"
done

echo 'Starting flower'
celery -A help_gamblers.taskapp --broker="${CELERY_BROKER_URL}" flower  --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
