# Generated by Django 4.0.3 on 2023-02-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('manual_flushing', models.BooleanField(default=False)),
                ('rtp', models.CharField(choices=[('NOT_STATED', 'NOT_STATED')], default='NOT_STATED', max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('established', models.DateField()),
                ('live_chat', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'casinos',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CasinoWithdrawalTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_times', to='casino.casino')),
            ],
            options={
                'unique_together': {('casino', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CasinoWithdrawalMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_methods', to='casino.casino')),
                ('withdrawal_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casino.withdrawalmethod')),
            ],
            options={
                'unique_together': {('casino', 'withdrawal_method')},
            },
        ),
        migrations.CreateModel(
            name='CasinoWithdrawalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_limits', to='casino.casino')),
            ],
            options={
                'unique_together': {('casino', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CasinoTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casino_types', to='casino.casino')),
                ('casino_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casino.types')),
            ],
            options={
                'unique_together': {('casino', 'casino_type')},
            },
        ),
        migrations.CreateModel(
            name='CasinoSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='casino.casino')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casino.software')),
            ],
            options={
                'unique_together': {('casino', 'software')},
            },
        ),
        migrations.CreateModel(
            name='CasinoRestrictedCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_countries', to='casino.casino')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
            ],
            options={
                'unique_together': {('casino', 'country')},
            },
        ),
        migrations.CreateModel(
            name='CasinoLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casino_licences', to='casino.casino')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.licence')),
            ],
            options={
                'unique_together': {('casino', 'licence')},
            },
        ),
        migrations.CreateModel(
            name='CasinoLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casino_languages', to='casino.casino')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language')),
            ],
            options={
                'unique_together': {('casino', 'language')},
            },
        ),
        migrations.CreateModel(
            name='CasinoDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='casino.casino')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casino.deposit')),
            ],
            options={
                'unique_together': {('casino', 'deposit')},
            },
        ),
        migrations.CreateModel(
            name='CasinoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casino_currencies', to='casino.casino')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
            ],
            options={
                'unique_together': {('casino', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='CasinoAffiliateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('affiliate_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casino.affiliateprogram')),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_programs', to='casino.casino')),
            ],
            options={
                'unique_together': {('casino', 'affiliate_program')},
            },
        ),
    ]
