# Generated by Django 4.0.3 on 2023-05-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='affiliate_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casino',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
