# Generated by Django 4.0.3 on 2023-05-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0002_casino_affiliate_link_casino_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='established',
            field=models.DateField(auto_now_add=True),
        ),
    ]
