# Generated by Django 4.0.3 on 2023-05-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0003_alter_casino_established'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
