# Generated by Django 4.0.3 on 2023-05-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0004_casino_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
