# Generated by Django 4.0.3 on 2023-05-20 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('casino', '0005_casino_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
    ]
