# Generated by Django 4.0.3 on 2023-05-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0006_casino_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoWhatWeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluses', to='casino.casino')),
            ],
            options={
                'unique_together': {('casino', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CasinoWhatWeDisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minuses', to='casino.casino')),
            ],
            options={
                'unique_together': {('casino', 'name')},
            },
        ),
    ]
