# Generated by Django 4.0.3 on 2023-05-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0007_casinowhatwelike_casinowhatwedislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
