# Generated by Django 4.0.3 on 2023-05-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0008_casino_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='live_gaming_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='mobile_gaming_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='payment_info_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='restricted_countries_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='security_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='support_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casino',
            name='virtual_games_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
